---
- name: Install required packages
  ansible.builtin.package:
    name: "{{ dronerunner_packages }}"
    state: present

- name: Create a symbolic link - git
  ansible.builtin.file:
    src: /usr/local/bin/git
    dest: /usr/bin/git
    owner: root
    group: wheel
    state: link

- name: Create a symbolic link - bash
  ansible.builtin.file:
    src: /usr/local/bin/bash
    dest: /bin/bash
    owner: root
    group: wheel
    state: link

- name: Create a symbolic link - python
  ansible.builtin.file:
    src: /usr/local/bin/python3.9
    dest: /usr/local/bin/python
    owner: root
    group: wheel
    state: link

- name: Create a symbolic link - g++ and clang++
  ansible.builtin.file:
    src: /usr/local/bin/{{ item.src }}
    dest: /usr/local/bin/{{ item.dest }}
    owner: root
    group: wheel
    state: link
  with_items:
    - {src: g++8, dest: g++-8}
    - {src: g++9, dest: g++-9}
    - {src: g++10, dest: g++-10}
    - {src: g++11, dest: g++-11}
    - {src: clang++10, dest: clang++-10}
    - {src: clang++11, dest: clang++-11}
    - {src: clang++12, dest: clang++-12}
    - {src: clang++13, dest: clang++-13}
    - {src: clang++14, dest: clang++-14}
    - {src: clang++15, dest: clang++-15}

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Add the user 'drone'
  ansible.builtin.user:
    name: "{{ dronerunner_user }}"

- name: Check for dronerunner
  ansible.builtin.stat:
    path: /usr/local/bin/drone-runner-exec
  register: drone_exec

- name: Download dronerunner
  ansible.builtin.get_url:
    url: https://github.com/drone-runners/drone-runner-exec/releases/latest/download/drone_runner_exec_freebsd_amd64.tar.gz
    dest: /tmp
    mode: "0770"
  when:
    - not drone_exec.stat.exists

- name: Extract archive  # noqa command-instead-of-module
  ansible.builtin.shell: |
    tar -xvf /tmp/drone_runner_exec_freebsd_amd64.tar.gz
    mv drone-runner-exec /usr/local/bin/drone-runner-exec
  changed_when: true
  when:
    - not drone_exec.stat.exists

- name: Create directory for drone
  ansible.builtin.file:
    path: /home/{{ dronerunner_user }}/.drone-runner-exec
    owner: "{{ dronerunner_user }}"
    group: "{{ dronerunner_user }}"
    mode: "0755"
    state: directory

- name: Install dronerunner config
  ansible.builtin.template:
    src: config_freebsd_agent
    dest: /home/{{ dronerunner_user }}/.drone-runner-exec/config
    owner: "{{ dronerunner_user }}"
    group: "{{ dronerunner_user }}"
    mode: "0644"
    force: false

- name: Install dronerunner service
  ansible.builtin.template:
    src: freebsd.rc
    dest: /etc/rc.d/dronerunner
    owner: root
    group: wheel
    mode: "0755"
  notify: start runner freebsd
