---
# From Aug 2021. Installed docker on base server ami.
# Now Aug 2022. Starting from "with Containers" ami and so fewer steps are required.
# Most of this is not needed.

- name: Install Nuget Package Provider
  ansible.windows.win_shell: Install-PackageProvider -Name "NuGet" -MinimumVersion "2.8.5.201" -Force
  changed_when: false

- name: Enable Windows Container Feature
  ansible.windows.win_feature:
    name: Containers
    state: present
  register: dockerwindowsfeature

- name: Reboot server if Windows Container Feature requires it
  ansible.windows.win_reboot:
  when: dockerwindowsfeature.reboot_required

# - name: Install Docker Msft Module
#   win_shell: Install-Module -Name "DockerMsftProvider" -Repository "PSGallery" -Force
#   changed_when: false

- name: Add a PowerShell module from a specific repository
  community.windows.win_psmodule:
    name: DockerMsftProvider
    repository: PSGallery
    state: present

- name: Install Docker package
  ansible.windows.win_shell: Install-Package –ProviderName "DockerMsftProvider" -Name "Docker" -Force
  args:
    creates: C:\Program Files\Docker\metadata.json
  register: dockerinstall
  notify: reboot windows

# why was this commented out? Seems like a good idea. Test again.
- name: Reboot server if Docker package requires it  # noqa no-handler
  ansible.windows.win_reboot:
  when: dockerinstall.changed

- name: Create script directory
  ansible.windows.win_file:
    path: "{{ dronerunner_scripts_dir_win }}"
    state: directory

- name: Install startdronerunner.sh script
  ansible.windows.win_template:
    src: startdronerunner.bat
    dest: "{{ dronerunner_scripts_dir_win }}\\startdronerunner.bat"
  notify: start runner windows

# Will this work, or must wait until after a reboot?
- name: Start docker service
  failed_when: false
  ansible.windows.win_shell: |
    Start-Service -Name "docker"

- name: Cron - determine number of server
  ansible.builtin.set_fact:
    drone_number_of_server: "{{ inventory_hostname_short | regex_search('(\\d+)$') }}"

- name: Create a scheduled task to reboot Weeks 1,3
  community.windows.win_scheduled_task:
    name: ScheduledReboot
    description: scheduledreboot
    actions:
      - path: shutdown
        arguments: /r
    triggers:
      - type: monthlydow
        weeks_of_month: 1,3
        months_of_year: january,february,march,april,may,june,july,august,september,october,november,december
        days_of_week: sunday
        start_boundary: "2017-10-09T09:00:00"
    username: Administrator
    password: "{{ dronerunner_machine_password }}"
    logon_type: s4u
    state: present
    enabled: true
  when:
    - drone_number_of_server|int % 2 == 1

- name: Create a scheduled task to reboot Weeks 2,4
  community.windows.win_scheduled_task:
    name: ScheduledReboot
    description: scheduledreboot
    actions:
      - path: shutdown
        arguments: /r
    triggers:
      - type: monthlydow
        weeks_of_month: 2,4
        months_of_year: january,february,march,april,may,june,july,august,september,october,november,december
        days_of_week: sunday
        start_boundary: "2017-10-09T09:00:00"
    username: Administrator
    password: "{{ dronerunner_machine_password }}"
    logon_type: s4u
    state: present
    enabled: true
  when:
    - drone_number_of_server|int % 2 == 0

# Will this work, or must wait until after a reboot?
- name: Pull images
  ansible.windows.win_shell: |
    docker pull cppalliance/dronevs2015:latest
    docker pull cppalliance/dronevs2017:latest
    docker pull cppalliance/dronevs2019:latest
    docker pull cppalliance/dronevs2022:latest
