---
- name: Start runner
  changed_when: true
  args:
    executable: /bin/bash
  ansible.builtin.shell:
    cmd: |
      docker stop runner || true
      docker rm runner || true
      /opt/drone/scripts/startdronerunner.sh

# could be modified...
- name: Start runner freebsd  # noqa command-instead-of-module
  changed_when: true
  args:
    executable: /bin/sh
  ansible.builtin.shell:
    cmd: |
      service dronerunner start

- name: Start runner windows
  ansible.windows.win_shell: |
    docker stop runner
    docker rm runner
    {{ dronerunner_scripts_dir_win }}\\startdronerunner.bat

- name: Reboot windows
  ansible.windows.win_reboot:

- name: Reboot mac
  ansible.builtin.reboot:
